#! /usr/bin/env python

import argparse
import sys
import httplib, urllib
import shutil
import datetime
from neurogenesis import demux
from neurogenesis import runner
from neurogenesis import extractor
from neurogenesis.util import Logger
from neurogenesis.base import serialize_sim_data, deserialize_sim_data, Simulation
from neurogenesis.plotter import plot_simulations

def main():
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("command", help="command to be executed. Possible values are: simulate, extract, plot, clean")
    arg_parser.add_argument("--inifile", help="specifies the location of the ini file to be executed.")
    arg_parser.add_argument("--outdir", help="specifies the location where files should be written to.")
    arg_parser.add_argument("--inetdir", help='location of the inet executable on NFS share')
    arg_parser.add_argument("--omnetdir", help="location of the omnet executable on NFS share")
    arg_parser.add_argument("--additionalFiles", nargs="+", help="additional Files which should be copied to the output dirs")
    arg_parser.add_argument("--nrRanks", help="Nr of ranks the simulation should be distributed to")
    arg_parser.add_argument("--mpiWorker", help="location of the MPI worker script")
    arg_parser.add_argument("--hostfile", help = "location of the host file")
    arg_parser.add_argument("--extractScalarsFile", help= "List of scalars to be extracted")
    arg_parser.add_argument("--extractVectorsFile", help= "List of vectors to be extracted")
    arg_parser.add_argument("--metaFile", help="Meta file where simulation metadata is stored")
    arg_parser.add_argument("--plotScript", help="location of the plot script")
    arg_parser.add_argument("--notificationKeyFile", help="location of the pushover keyfile")
    arg_parser.add_argument("--ignore", help="Token is ignored")
    arg_parser.add_argument("--name", help="name that is used to identify the simulation run later")
    arg_parser.add_argument("--configName", help="name of the config in ini to execute")
    args = arg_parser.parse_args()
    args = write_default_parameters(args)

    if args.command == "simulate":
        Logger.info("trying to purge old simulation data...")
        clean_old_configs(args)
        Logger.info("Creating simulation configs...")
        sim = Simulation()
        sim.last_executed = datetime.datetime.now()

        if args.name is not None:
            sim.name = args.name

        runs = write_sim_config(args)
        runs = run_simulation(args, runs)
        Logger.info("Saving simulation Metadata")
        sim.simulation_runs = runs
        serialize_sim_data(args.metaFile, sim)
        send_notification(args)

    elif args.command == "extract":
        Logger.info("Extracting Scalars")
        updated_simulations = extract(args)
        Logger.info("done. Writing results back to metafile")
        serialize_sim_data(args.metaFile, updated_simulations)

    elif args.command == "plot":
        plot_simfile(args)

    elif args.command == "clean":
        Logger.info("trying to purge old simulation data...")
        clean_old_configs(args)

    else:
        Logger.error("Invlaid command: %s" % str(args.command))

def run_simulation(args, simulations):
        Logger.info("Starting distributed Simulation with %i ranks" % args.nrRanks)
        return runner.run_simulation(args.mpiWorker, args.hostfile, args.nrRanks, simulations)



def extract(args):
    simulation = deserialize_sim_data(args.metaFile)
    simulations = simulation.simulation_runs
    try:
        simulations = extractor.extract(args.extractScalarsFile, simulations)
    except IOError as e:
        Logger.warning("Can't read scalars file: %s, exception: %s" % (args.extractScalarsFile, e.strerror))
    try:
        simulations = extractor.extract_vectors(args.extractVectorsFile, simulations)
    except IOError as e:
        Logger.warning("Can't read vectors file: %s, exception: %s" % (args.extractVectorsFile, e.strerror))
    simulation.simulation_runs = simulations
    return simulation


def plot_simfile(args):
    simulations = deserialize_sim_data(args.metaFile)
    plot_simulations(simulations, args.plotScript)

def write_sim_config(args):
    if args.inifile is None:
        Logger.error("No ini File specified!")
        sys.exit(-127)
    simulations = demux.demux_and_write_simulation(args)
    return simulations

def clean_old_configs(args):
    try:
        simulations = deserialize_sim_data(args.metaFile)
    except IOError as e:
        Logger.info("no previous simulations found")
        return

    Logger.info("purging old simulation data")
    for simulation in simulations.simulation_runs.values():
        shutil.rmtree(simulation.path, ignore_errors=True)

def send_notification(args):
    try:
        pushover_secret_file = open(args.notificationKeyFile, "r")
    except IOError:
        Logger.warning("pushover secret-file does not exist")
        return
    secret = pushover_secret_file.read().strip()
    conn = httplib.HTTPSConnection("api.pushover.net:443")
    conn.request("POST", "/1/messages.json",
    urllib.urlencode({
    "token": "ae1u9qxnk2obfgiodr19rrbo2bsazs",
    "user": secret,
    "message": "simulation of file %s with %s ranks finished!" % (args.inifile, args.nrRanks),
  }), { "Content-type": "application/x-www-form-urlencoded" })
    conn.getresponse()

    pushover_secret_file.close()

def write_default_parameters(args):
    if args.mpiWorker is None:
        args.mpiWorker = "/mnt/distsim/simtools/mpiworker"

    if args.hostfile  is None:
        args.hostfile = "/mnt/distsim/simtools/hostfile"

    #automatically parses hostfile to get the correct number of ranks
    if args.nrRanks is None:
        try:
            with open(args.hostfile, "r") as f:
                h = [[y.split("=") for y in x.strip().split()] for x in f if len(x.strip()) > 1 and x[0] != '#']
            args.nrRanks = reduce(lambda x,y: x+int(y[1][1]), h, 0)
        except IOError as e:
            Logger.warning("No hostfile specified and default location %s not present!" % (args.hostfile))
            args.nrRanks = 0

    if args.outdir is None:
        args.outdir = "/mnt/distsim/simulations/"

    if args.inetdir is None:
        args.inetdir = "/mnt/distsim/inet/src/"

    additional_files = []

    if args.additionalFiles is not None:
        for file in args.additionalFiles:
            additional_files.append(file)
    args.additionalFiles = additional_files

    if args.omnetdir is None:
        args.omnetdir = "/mnt/distsim/omnetpp-5.0/"
    args.omnetdir += "bin/opp_run"

    if args.extractScalarsFile is None:
        args.extractScalarsFile = "scalars.txt"

    if args.extractVectorsFile is None:
        args.extractVectorsFile = "vectors.txt"

    if args.metaFile is None:
        args.metaFile = "meta.pickle"

    if args.plotScript is None:
        args.plotScript = "plot.py"

    if args.notificationKeyFile is None:
        args.notificationKeyFile = "pushover_secret"

    if args.configName is None:
        args.configName = "General"
    return args

if __name__ == '__main__':
    main()
