#!/usr/bin/env  python
import sys
from subprocess import call

from mpi4py import MPI

from neurogenesis.cluster import MPITags, Cluster
from neurogenesis.util import Logger


def main():
    comm = MPI.Comm.Get_parent().Merge()
    print("started worker %s" % (comm.Get_rank()))
    comm.Barrier()
    while True:

        reception_status = MPI.Status()
        task = comm.recv(source=MPI.ANY_SOURCE, tag=MPI.ANY_TAG, status=reception_status)
        # execute task
        if reception_status.Get_tag() == MPITags.WORK:
            task.last_exit_code = call(task.executable_path, shell=True)
            task.last_executed_on_rank = comm.Get_rank()
            comm.send(task, Cluster.MASTER_CONTROLLER, MPITags.FEEDBACK)
        elif reception_status.Get_tag() == MPITags.DIE:
            Logger.debug("rank %s exiting" % (comm.Get_rank()))
            sys.exit(0)
        else:
            Logger.error("Unknown TAG received!")


if __name__ == '__main__':
    main()
