#!/bin/python
import sys
from mpi4py import MPI
from neurogenesis.util import Logger, PrintColors
from neurogenesis.cluster import MPITags, Cluster, TaskQueue


def main():
    comm = MPI.Comm.Get_parent().Merge()
    print("started worker %s" % (comm.Get_rank()))
    comm.Barrier()
    while True:

        reception_status = MPI.Status()
        task = comm.recv(source=MPI.ANY_SOURCE, tag=MPI.ANY_TAG, status=reception_status)
        # execute task
        if reception_status.Get_tag() == MPITags.WORK:
            return_value = 0
            print(task)
            comm.send(return_value, Cluster.MASTER_CONTROLLER, MPITags.FEEDBACK)
        elif reception_status.Get_tag() == MPITags.DIE:
            Logger.debug("rank %s exiting" %  (comm.Get_rank()))
            sys.exit(0)
        else:
            Logger.error("Unknown TAG received!")

if __name__ == '__main__':
        main()
